# Generated by Django 5.2.1 on 2025-05-16 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoryMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Human", "Human"), ("AI", "AI")], max_length=10
                    ),
                ),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "tool_call_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "history_message",
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Messure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("meter_id", models.IntegerField()),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("sample", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "observation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("last_message_datetime", models.DateTimeField()),
                ("last_notification_datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="SessionMessure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.DateTimeField(blank=True, max_length=255, null=True),
                ),
                (
                    "messure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="piragua_chat.messure",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="piragua_chat.session",
                    ),
                ),
            ],
            options={
                "db_table": "session_messure",
            },
        ),
    ]
