name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag piragua-chat:$(date +%s)
    - uses: kciter/aws-ecr-action@v5
      with:
        # The AWS access key id
        access_key_id: ${{ secrets.AwsAccessKey }}
        # The AWS secret access key
        secret_access_key: ${{ secrets.AwsSecretKey }}
        # AWS Account ID
        account_id: ${{ secrets.AwsAccountId }}
        # A comma-delimited list of AWS account IDs that are associated with the ECR registries. If you do not specify a registry, the default ECR registry is assumed
        # Name of your ECR repository
        repo: "test-piragua"
        # The AWS region
        region: "us-east-2"
        # Extra flags to pass to docker build (see docs.docker.com/engine/reference/commandline/build)
        #extra_build_args: # optional, default is 
        # Images to use as cache for the docker build (see `--cache-from` argument docs.docker.com/engine/reference/commandline/build)
